USE [master]
GO

/****** Object:  Database [ESP_GearGuard]    Script Date: 12/28/2021 3:15:52 PM ******/
CREATE DATABASE [ESP_GearGuard]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GearGuard', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\GearGuard.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GearGuard_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\GearGuard_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ESP_GearGuard].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ESP_GearGuard] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ESP_GearGuard] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ESP_GearGuard] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ESP_GearGuard] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ESP_GearGuard] SET ARITHABORT OFF 
GO

ALTER DATABASE [ESP_GearGuard] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ESP_GearGuard] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ESP_GearGuard] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ESP_GearGuard] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ESP_GearGuard] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ESP_GearGuard] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ESP_GearGuard] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ESP_GearGuard] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ESP_GearGuard] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ESP_GearGuard] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ESP_GearGuard] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ESP_GearGuard] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ESP_GearGuard] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ESP_GearGuard] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ESP_GearGuard] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ESP_GearGuard] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ESP_GearGuard] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ESP_GearGuard] SET RECOVERY FULL 
GO

ALTER DATABASE [ESP_GearGuard] SET  MULTI_USER 
GO

ALTER DATABASE [ESP_GearGuard] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ESP_GearGuard] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ESP_GearGuard] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ESP_GearGuard] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ESP_GearGuard] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ESP_GearGuard] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ESP_GearGuard] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ESP_GearGuard] SET  READ_WRITE 
GO

