USE [ESP_Events]
GO

/****** Object:  Table [dbo].[LocationRooms]    Script Date: 12/28/2021 10:29:53 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LocationRooms](
	[LocationRoomID] [int] IDENTITY(1,1) NOT NULL,
	[LocationId] [int] NOT NULL,
	[RoomId] [int] NOT NULL,
 CONSTRAINT [PK_LocationRooms] PRIMARY KEY CLUSTERED 
(
	[LocationRoomID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

