USE [master]
GO

/****** Object:  Database [ESP_Events]    Script Date: 12/28/2021 1:04:40 PM ******/
CREATE DATABASE [ESP_Events]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ESP_Events', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ESP_Events.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ESP_Events_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ESP_Events_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ESP_Events].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ESP_Events] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ESP_Events] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ESP_Events] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ESP_Events] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ESP_Events] SET ARITHABORT OFF 
GO

ALTER DATABASE [ESP_Events] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ESP_Events] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ESP_Events] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ESP_Events] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ESP_Events] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ESP_Events] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ESP_Events] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ESP_Events] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ESP_Events] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ESP_Events] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ESP_Events] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ESP_Events] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ESP_Events] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ESP_Events] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ESP_Events] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ESP_Events] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ESP_Events] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ESP_Events] SET RECOVERY FULL 
GO

ALTER DATABASE [ESP_Events] SET  MULTI_USER 
GO

ALTER DATABASE [ESP_Events] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ESP_Events] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ESP_Events] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ESP_Events] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ESP_Events] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ESP_Events] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ESP_Events] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ESP_Events] SET  READ_WRITE 
GO

