//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventSpaceproduction.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailSetting
    {
        public int Id { get; set; }
        public string EmailType { get; set; }
        public string EmailServer { get; set; }
        public string Port { get; set; }
        public string EmailLogin { get; set; }
        public string EmailPassword { get; set; }
        public string EmailSecurity { get; set; }
        public bool Enabled { get; set; }
    }
}
