//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventSpaceproduction.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicenseType
    {
        public int LicenseTypeID { get; set; }
        public int LicenseID { get; set; }
        public string License_Name { get; set; }
        public int License_Count { get; set; }
    }
}
