//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventSpaceproduction.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationRoom
    {
        public int LocationRoomID { get; set; }
        public int LocationId { get; set; }
        public int RoomId { get; set; }
    }
}
