//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventSpaceproduction.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Policy
    {
        public int Id { get; set; }
        public string PolicyName { get; set; }
        public string PolicyType { get; set; }
        public string PolicyEstablishedDate { get; set; }
        public int PolicyEstablishedByUserId { get; set; }
        public string policyValue { get; set; }
        public bool Active { get; set; }
    }
}
