//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventSpaceproduction.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public int RoomId { get; set; }
        public string Room_Name { get; set; }
        public System.TimeSpan Operations_Start { get; set; }
        public System.TimeSpan Operations_End { get; set; }
        public bool Active { get; set; }
        public int Image { get; set; }
    }
}
