USE [ESP_GearGuard]
GO

/****** Object:  Table [dbo].[Libraries]    Script Date: 12/28/2021 3:42:47 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Libraries](
	[LibraryId] [int] IDENTITY(1,1) NOT NULL,
	[Library Name] [varchar](200) NOT NULL,
	[Library Description] [varchar](250) NOT NULL,
 CONSTRAINT [PK_Libraries] PRIMARY KEY CLUSTERED 
(
	[LibraryId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

