USE [ESP_GearGuard]
GO

/****** Object:  Table [dbo].[LibraryRooms]    Script Date: 12/29/2021 3:10:51 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LibraryRooms](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[LibraryId] [int] NOT NULL,
	[EventId] [int] NOT NULL,
	[RoomId] [int] NOT NULL,
 CONSTRAINT [PK_LibraryRooms] PRIMARY KEY CLUSTERED 
(
	[LibraryId] ASC,
	[EventId] ASC,
	[RoomId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

